language: java
os: linux
dist: trusty

before_install:
  - sh travis/create_gpg_key.sh

jobs:
  include:
    - stage: Test and Coverage
      script: "mvn clean install -f WakeOnLanHTTPRest -Dgpg.skip "
      after_success:
        - bash <(curl -s https://codecov.io/bash)
        - bash <(curl -Ls https://coverage.codacy.com/get.sh)
