language: java
os: linux
dist: trusty

before_install:
  - sh .travis/init.sh

jobs:
  include:
    - stage: Deploy Release
      script: "mvn clean release:prepare release:perform --batch-mode --settings .travis/settings.xml -f WakeOnLanHTTPRest -DskipTests"
      if: branch = master
