language: java
os: linux
dist: trusty

before_install:
  - sudo apt-get -y install gpgv2 maven
  - sh .travis/init.sh

jobs:
  include:
    - stage: Test and Coverage
      script: "mvn clean test -f WakeOnLanHTTPRest -Dgpg.skip"
      after_success:
        - bash <(curl -s https://codecov.io/bash)
        - bash <(curl -Ls https://coverage.codacy.com/get.sh)
    - stage: SonarCloud
      script: "mvn clean verify sonar:sonar -Dsonar.projectKey=WakeOnLanHTTPRest -Dgpg.skip"
    - stage: Deploy Snapshot
      script: "mvn clean deploy --settings .travis/settings.xml -f WakeOnLanHTTPRest -DskipTests,gpg.skip"
      after_success:
        - bash <(curl -s https://codecov.io/bash)
        - bash <(curl -Ls https://coverage.codacy.com/get.sh)

