language: java
sudo: false
script: mvn clean install -f WakeOnLanHTTPRest
jdk:
  - oraclejdk11
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash <(curl -Ls https://coverage.codacy.com/get.sh)

