language: java
os: linux
dist: trusty

before_install:
  - sh .travis/init.sh

jobs:
  include:
    - stage: Test and Coverage
      script: "mvn clean test -f WakeOnLanHTTPRest -Dgpg.skip"
      after_success:
        - bash <(curl -s https://codecov.io/bash)
        - bash <(curl -Ls https://coverage.codacy.com/get.sh)
    - stage: Deploy Snapshot
      script: "mvn clean deploy --settings .travis/settings.xml -f WakeOnLanHTTPRest -DskipTests,gpg.skip"
      after_success:
        - bash <(curl -s https://codecov.io/bash)
        - bash <(curl -Ls https://coverage.codacy.com/get.sh)
    - stage: Deploy Release
      script: "mvn clean release:prepare release:perform -Dresume=false --batch-mode --settings .travis/settings.xml -f WakeOnLanHTTPRest -DskipTests"
      after_success:
        - git push
      if: (branch = master) AND (tag IS blank)
