name: Build

on:
  push:
    branches: '*'
  pull_request:
    branches: [ master ]
  schedule:
  - cron: "0 * * * *"

jobs:
  Test_and_Deploy:
    name: Test and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Configure M2
      run: 
        mkdir -p ~/.m2;
        echo "<settings><servers><server><id>ossrh</id><username>${{ secrets.OSSRH_USERNAME }}</username><password>${{ secrets.OSSRH_TOKEN }}</password></server></servers></settings>" > ~/.m2/settings.xml
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn clean package -f WakeOnLanHTTPRest -Dgpg.skip
    - name: Push Coverage
      uses: codecov/codecov-action@v1
      with:
        directory: ./WakeOnLanHTTPRest/
    - name: Release Snapshot
      run: mvn clean deploy -f WakeOnLanHTTPRest -Dgpg.skip 
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
  Analyze_Code:
    name: Analyze Code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -f WakeOnLanHTTPRest -Dgpg.skip
  github_security_analyze:
      name: GitHub Secuity Analyze
      runs-on: ubuntu-latest
      permissions:
        actions: read
        contents: read
        security-events: write
      strategy:
        fail-fast: false
      steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: java
      - name: Autobuild
        uses: github/codeql-action/autobuild@v1
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
